"""
car.py — F1 Telemetry Simulator
================================
Simulates a Formula 1 car broadcasting live sensor data over UDP at
configurable rates. Each packet is a 32-byte binary payload using a
custom protocol designed for microsecond-latency ingestion.

Packet layout (struct format: '!Qddq' = big-endian):
  Offset  Size  Type            Field
  ------  ----  ----            -----
  0       8     uint64          timestamp_ns  (nanoseconds since epoch)
  8       8     float64         speed_kph     (0.0 – 360.0)
  16      8     float64         engine_rpm    (0.0 – 15000.0)
  24      8     int64           seq           (monotonically increasing)

Total: 32 bytes per packet.

Why UDP?
  UDP is connectionless — it fires and forgets without waiting for
  acknowledgment. At 5,000+ packets/sec, the ACK overhead of TCP
  would create a bottleneck. Some packet loss is acceptable for sensor
  data; the seq# field lets us detect gaps on the receiver side.

Why a sequence number?
  Without seq, the receiver has no way to detect dropped packets or
  distinguish a crash from a quiet moment. With seq, validate.py can
  assert perfect continuity and report the exact packet where data
  was lost.

Usage:
  python car.py                        # default: 5000 pps to localhost
  python car.py --host 192.168.1.10   # target a remote primary node
  python car.py --pps 1000            # slower rate for debugging
  python car.py --pps 10000           # stress test
  python car.py --lap monaco          # Monaco circuit profile
"""

import socket
import struct
import time
import math
import argparse
import random
import sys

# ─── Protocol constants ───────────────────────────────────────────────────────

PRIMARY_HOST = "127.0.0.1"
PRIMARY_PORT = 9000
PACKET_FORMAT = "!Qddq"          # big-endian: uint64, double, double, int64
PACKET_SIZE   = struct.calcsize(PACKET_FORMAT)  # == 32 bytes

# ─── Circuit profiles ─────────────────────────────────────────────────────────
# Each profile defines a lap as a list of (duration_sec, target_speed_kph,
# target_rpm) waypoints. The simulator interpolates between them smoothly.
# This gives realistic telemetry that varies like a real circuit rather than
# random noise.

CIRCUITS = {
    "monaco": [
        # Sector 1: Start/finish straight → tight hairpin complex
        (3.0,  295, 14800),   # launch down pit straight
        (1.5,   60,  9200),   # Sainte Dévote braking
        (4.0,  130, 11500),   # Casino Square climb
        (2.0,   50,  8000),   # Grand Hotel hairpin — slowest corner
        (5.0,  165, 12200),   # Portier → tunnel
        # Sector 2: Tunnel — fastest section of Monaco
        (2.5,  290, 14700),   # tunnel flat-out
        (1.5,   80,  9500),   # Nouvelle Chicane heavy braking
        (3.0,  145, 11800),   # Tabac
        # Sector 3: Swimming pool complex
        (2.0,   95, 10200),   # Swimming Pool S1
        (1.5,  115, 10800),   # Swimming Pool S2
        (2.0,   65,  8800),   # Rascasse hairpin
        (1.5,   95, 10000),   # Anthony Noghès
        (2.0,  240, 13500),   # Back onto pit straight
    ],
    "monza": [
        # Temple of Speed — long straights, brutal braking
        (6.0,  350, 14900),   # main straight flat-out
        (1.0,   70,  9000),   # Variante del Rettifilo braking
        (3.0,  200, 13000),   # Curva Grande
        (1.5,   95, 10000),   # Variante della Roggia
        (4.0,  280, 14500),   # Lesmo 1 & 2
        (1.0,   80,  9200),   # Variante Ascari
        (5.0,  335, 14800),   # back straight
        (1.5,   65,  8800),   # Parabolica braking
        (3.0,  195, 12800),   # Parabolica exit
    ],
    "silverstone": [
        # High-speed sweepers
        (4.0,  295, 14700),   # Vale → Club straight
        (2.0,  185, 12500),   # Abbey
        (3.0,  225, 13200),   # Farm curve
        (1.5,  145, 11500),   # Village
        (2.5,  195, 12800),   # Loop
        (3.0,  265, 14200),   # Aintree → Wellington
        (2.0,  215, 13000),   # Brooklands
        (1.5,  165, 12000),   # Luffield
        (4.0,  310, 14800),   # Woodcote → Copse flat
        (2.0,  175, 12200),   # Maggotts/Becketts entry
        (3.0,  250, 13800),   # Chapel
    ],
}

# ─── Simulator core ───────────────────────────────────────────────────────────

class F1Simulator:
    """
    Simulates an F1 car driving a circuit lap-by-lap.

    Telemetry is generated by interpolating through circuit waypoints,
    with small amounts of Gaussian noise added to speed and RPM to mimic
    real sensor jitter. Wheel slip and DRS effects are layered on top.
    """

    def __init__(self, circuit: str = "monaco"):
        self.circuit   = circuit
        self.waypoints = CIRCUITS[circuit]
        self.seq       = 0
        self.lap       = 0
        self._build_timeline()

    def _build_timeline(self):
        """Pre-compute the full lap as a flat list of (time, speed, rpm) frames
        at 1ms resolution. This lets us interpolate without per-packet math."""
        self.timeline = []
        for (duration, target_spd, target_rpm) in self.waypoints:
            steps = max(1, int(duration * 1000))  # 1ms resolution
            for i in range(steps):
                t = i / steps
                # smooth step interpolation (ease in/out)
                t_smooth = t * t * (3 - 2 * t)
                prev = self.timeline[-1] if self.timeline else (target_spd, target_rpm)
                spd = prev[0] + (target_spd - prev[0]) * t_smooth
                rpm = prev[1] + (target_rpm - prev[1]) * t_smooth
                self.timeline.append((spd, rpm))
        self.lap_duration_ms = len(self.timeline)
        self.frame_idx = 0

    def _next_frame(self):
        """Advance one frame and return (speed_kph, engine_rpm)."""
        spd, rpm = self.timeline[self.frame_idx]
        self.frame_idx += 1
        if self.frame_idx >= self.lap_duration_ms:
            self.frame_idx = 0
            self.lap += 1
            print(f"  [car] Lap {self.lap} complete. "
                  f"Resuming from frame 0 of {self.lap_duration_ms} frames.")
        # Add realistic sensor jitter (Gaussian noise)
        spd = max(0, spd + random.gauss(0, 1.2))
        rpm = max(0, rpm + random.gauss(0, 80))
        return spd, rpm

    def build_packet(self) -> bytes:
        """Pack the next telemetry frame into a 32-byte binary payload."""
        speed, rpm   = self._next_frame()
        timestamp_ns = time.time_ns()
        self.seq    += 1
        return struct.pack(PACKET_FORMAT, timestamp_ns, speed, rpm, self.seq)


# ─── Transmission loop ────────────────────────────────────────────────────────

def run(host: str, port: int, pps: int, circuit: str):
    """
    Open a UDP socket and fire packets at the target rate.

    Rate limiting is done with a high-precision sleep loop rather than
    time.sleep(1/pps) to avoid cumulative drift — we track the next
    scheduled send time and sleep only the remaining delta.
    """
    sim = F1Simulator(circuit=circuit)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    interval_ns = 1_000_000_000 // pps   # nanoseconds between packets
    next_send   = time.time_ns()

    print(f"  [car] F1 Telemetry Simulator")
    print(f"  [car] Circuit  : {circuit.upper()}")
    print(f"  [car] Target   : {host}:{port}")
    print(f"  [car] Rate     : {pps:,} packets/sec  ({PACKET_SIZE} bytes each)")
    print(f"  [car] Lap time : ~{sim.lap_duration_ms/1000:.1f}s of telemetry data")
    print(f"  [car] Protocol : struct '{PACKET_FORMAT}' · {PACKET_SIZE} bytes/packet")
    print()

    sent        = 0
    report_every = pps  # print stats once per second
    t_start     = time.time()

    try:
        while True:
            packet = sim.build_packet()
            sock.sendto(packet, (host, port))
            sent += 1

            if sent % report_every == 0:
                elapsed = time.time() - t_start
                actual_pps = sent / elapsed
                speed, rpm = struct.unpack(PACKET_FORMAT, packet)[1:3]
                seq        = struct.unpack(PACKET_FORMAT, packet)[3]
                print(
                    f"  seq={seq:>8,}  "
                    f"speed={speed:>6.1f} kph  "
                    f"rpm={rpm:>6.0f}  "
                    f"actual={actual_pps:>6.0f} pps  "
                    f"lap={sim.lap}"
                )

            # High-precision rate limiter
            next_send += interval_ns
            now = time.time_ns()
            if next_send > now:
                time.sleep((next_send - now) / 1_000_000_000)

    except KeyboardInterrupt:
        elapsed = time.time() - t_start
        print(f"\n  [car] Stopped. Sent {sent:,} packets in {elapsed:.1f}s "
              f"({sent/elapsed:,.0f} pps average)")
    finally:
        sock.close()


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="F1 Telemetry Simulator — streams binary UDP packets to primary.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  python car.py                          default: Monaco, 5000 pps, localhost
  python car.py --circuit monza          Monza circuit profile (higher top speeds)
  python car.py --pps 1000              slow mode for debugging
  python car.py --pps 10000             stress test the ingestion layer
  python car.py --host 192.168.1.5      target a remote primary node
        """
    )
    parser.add_argument("--host",    default=PRIMARY_HOST,
                        help="Primary node IP (default: 127.0.0.1)")
    parser.add_argument("--port",    type=int, default=PRIMARY_PORT,
                        help="Primary node UDP port (default: 9000)")
    parser.add_argument("--pps",     type=int, default=5000,
                        help="Packets per second (default: 5000)")
    parser.add_argument("--circuit", default="monaco",
                        choices=list(CIRCUITS.keys()),
                        help="Circuit profile to simulate (default: monaco)")
    args = parser.parse_args()

    run(args.host, args.port, args.pps, args.circuit)


if __name__ == "__main__":
    main()
